// google.js
//
// Every Google call in one place. v1 duplicated getAccessToken() four times
// and fired 41 unthrottled requests at Gmail; this fixes both.
//
// API-budget decisions live here:
//   - the access token is cached in memory until ~1 min before it expires,
//     so a full run costs ONE token exchange instead of one per source
//   - Gmail messages are fetched with format=metadata and an explicit header
//     whitelist, not format=full, for the FIRST pass over everything new —
//     we only need the headers/snippet to triage, and this is roughly an
//     order of magnitude less data. format=full (see getMessagesBody) is
//     used for a SECOND pass, only over whatever survived triage (usually
//     0-5 messages) — so the number of full fetches stays cheap even
//     though each one is bigger.
//   - requests run through a small concurrency pool, not Promise.all
//   - the calendar list is cached to disk for a day; it changes ~never

import axios from "axios";
import { logger } from "./log.js";
import { getMeta, setMeta } from "./store.js";

const log = logger("google");
const TIMEOUT = 15000;

let tokenCache = { value: null, expiresAt: 0 };

/**
 * Turns an axios error from a Google endpoint into the specific reason,
 * instead of the generic "Request failed with status code 400" axios
 * hands back by default — which is all `err.message` ever carried before,
 * and all that ever reached the Sources panel or `npm run doctor` (see
 * brief/compose.js's runSources, which stores `err.message` verbatim as
 * the source's lastError). Google's own error bodies already say exactly
 * what's wrong; this just stops throwing that away.
 *
 * Two response shapes to account for: the OAuth token endpoint's own
 * `{ error, error_description }` (e.g. invalid_grant — a dead refresh
 * token) and the regular Gmail/Calendar API's `{ error: { message } }`.
 * Falls back to the plain HTTP status, then to axios's own message if
 * there's no response at all (a timeout, DNS failure, offline Pi).
 */
export function googleErrorMessage(err) {
  const data = err.response?.data;
  if (data?.error_description) return `${data.error} — ${data.error_description}`;
  if (data?.error?.message) return `${data.error.message} (HTTP ${err.response.status})`;
  if (err.response) return `HTTP ${err.response.status} ${err.response.statusText || ""}`.trim();
  return err.message;
}

export async function getAccessToken() {
  if (tokenCache.value && Date.now() < tokenCache.expiresAt) return tokenCache.value;

  const { GMAIL_REFRESH_TOKEN, GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET } = process.env;
  if (!GMAIL_REFRESH_TOKEN || !GMAIL_CLIENT_ID || !GMAIL_CLIENT_SECRET) {
    throw new Error("Google credentials missing — .env needs GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET, GMAIL_REFRESH_TOKEN");
  }

  let res;
  try {
    res = await axios.post(
      "https://oauth2.googleapis.com/token",
      {
        client_id: GMAIL_CLIENT_ID,
        client_secret: GMAIL_CLIENT_SECRET,
        refresh_token: GMAIL_REFRESH_TOKEN,
        grant_type: "refresh_token",
      },
      { timeout: TIMEOUT }
    );
  } catch (err) {
    // invalid_grant here means the refresh token itself is dead — expired
    // (Google auto-expires a refresh token from an unverified/"Testing"
    // OAuth client after 7 days of disuse, or after 6 months regardless of
    // use), revoked (a Google password change, or pulling the app's access
    // under myaccount.google.com/permissions), or the client secret was
    // rotated in Google Cloud Console. None of those are transient — no
    // retry fixes it, GMAIL_REFRESH_TOKEN in .env has to be regenerated by
    // going through the consent screen again. Both Gmail and Calendar share
    // this one call, which is why they always fail together with the same
    // error the moment this token dies, while Money (no Google dependency
    // at all) keeps working.
    throw new Error(`Google token refresh failed — ${googleErrorMessage(err)}`);
  }

  const expiresIn = res.data.expires_in || 3600;
  tokenCache = { value: res.data.access_token, expiresAt: Date.now() + (expiresIn - 60) * 1000 };
  log.debug("access token refreshed");
  return tokenCache.value;
}

/** Run tasks with bounded concurrency. Gentler on quota than Promise.all. */
async function pool(items, limit, worker) {
  const out = new Array(items.length);
  let cursor = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const i = cursor++;
      try {
        out[i] = await worker(items[i], i);
      } catch (err) {
        out[i] = null;
        log.warn(`task ${i} failed: ${err.message}`);
      }
    }
  });
  await Promise.all(runners);
  return out;
}

async function authed(url, params, token) {
  try {
    const res = await axios.get(url, {
      headers: { Authorization: `Bearer ${token}` },
      params,
      timeout: TIMEOUT,
    });
    return res.data;
  } catch (err) {
    // Same enrichment as getAccessToken()'s own catch, for calls that get
    // past the token exchange but still fail — a scope the token was never
    // granted, an API not enabled on the Cloud project, a bad calendar id.
    throw new Error(`Google request failed — ${googleErrorMessage(err)}`);
  }
}

// ----------------------------------------------------------------- Gmail

/** Just the ids. One cheap call; we filter against memory before fetching bodies. */
export async function listMessageIds({ query, maxResults = 40 }) {
  const token = await getAccessToken();
  const data = await authed(
    "https://www.googleapis.com/gmail/v1/users/me/messages",
    { q: query, maxResults },
    token
  );
  return (data.messages || []).map((m) => m.id);
}

const WANTED_HEADERS = ["From", "To", "Subject", "Date", "List-Unsubscribe", "Reply-To"];

/**
 * Headers + snippet only. This is all the classifier needs, and it keeps the
 * payload small enough that fetching 20 messages is genuinely cheap.
 */
export async function getMessagesMetadata(ids, { concurrency = 5 } = {}) {
  if (!ids.length) return [];
  const token = await getAccessToken();

  const results = await pool(ids, concurrency, async (id) => {
    const data = await authed(
      `https://www.googleapis.com/gmail/v1/users/me/messages/${id}`,
      { format: "metadata", metadataHeaders: WANTED_HEADERS },
      token
    );
    const h = Object.fromEntries(
      (data.payload?.headers || []).map((x) => [x.name.toLowerCase(), x.value])
    );
    return {
      id: data.id,
      threadId: data.threadId,
      labelIds: data.labelIds || [],
      snippet: (data.snippet || "").trim(),
      from: h.from || "",
      to: h.to || "",
      subject: h.subject || "(no subject)",
      date: h.date || "",
      replyTo: h["reply-to"] || "",
      isNewsletter: Boolean(h["list-unsubscribe"]),
      internalDate: data.internalDate ? Number(data.internalDate) : null,
    };
  });

  return results.filter(Boolean);
}

function decodeBase64Url(data) {
  if (!data) return "";
  try {
    return Buffer.from(data.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf-8");
  } catch {
    return "";
  }
}

/**
 * A crude but adequate HTML→text pass for the (common) case a message has
 * no text/plain part at all — just enough to give the AI classifier real
 * sentences instead of tag soup. Not meant to render anywhere.
 */
function stripHtml(html) {
  return html
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/<\/(p|div|tr|li)>/gi, "\n")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/gi, '"')
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

/**
 * Depth-first search through a Gmail message's (possibly multipart) payload
 * for its body text — text/plain wins if there is one, text/html run
 * through stripHtml() otherwise. Exported for its own tests; not meant to
 * be called with anything but a real Gmail `payload` object.
 */
export function findBodyText(payload) {
  if (!payload) return "";
  const stack = [payload];
  let plain = "";
  let html = "";
  while (stack.length) {
    const part = stack.pop();
    if (part.parts) stack.push(...part.parts);
    if (!plain && part.mimeType === "text/plain" && part.body?.data) {
      plain = decodeBase64Url(part.body.data);
    } else if (!html && part.mimeType === "text/html" && part.body?.data) {
      html = decodeBase64Url(part.body.data);
    }
  }
  if (plain.trim()) return plain.trim();
  if (html.trim()) return stripHtml(html);
  return "";
}

/**
 * Full body text for a SMALL set of messages — only ever called for
 * whatever survived triage (see sources/email.js), never the whole
 * fetched batch. format=full is roughly an order of magnitude more data
 * per message than the metadata-only fetch above; the cost-control
 * comment at the top of this file still holds because it's the NUMBER of
 * full fetches that stays small, not the size of any one of them.
 * Returns a Map from message id to its plain-text body (empty string if
 * a particular message has none, or its own fetch failed).
 */
export async function getMessagesBody(ids, { concurrency = 5 } = {}) {
  if (!ids.length) return new Map();
  const token = await getAccessToken();

  const results = await pool(ids, concurrency, async (id) => {
    const data = await authed(
      `https://www.googleapis.com/gmail/v1/users/me/messages/${id}`,
      { format: "full" },
      token
    );
    return [data.id, findBodyText(data.payload)];
  });

  return new Map(results.filter(Boolean));
}

// -------------------------------------------------------------- Calendar

/** Calendar list changes ~never, so cache it for a day and save a call per run. */
export async function getCalendarList({ ttlHours = 24, force = false } = {}) {
  const cached = await getMeta("calendarList");
  if (!force && cached && Date.now() - new Date(cached.at).getTime() < ttlHours * 3600000) {
    return cached.items;
  }

  const token = await getAccessToken();
  const data = await authed(
    "https://www.googleapis.com/calendar/v3/users/me/calendarList",
    { minAccessRole: "reader", maxResults: 250 },
    token
  );
  const items = (data.items || []).map((c) => ({ id: c.id, summary: c.summary, color: c.backgroundColor || null }));
  await setMeta("calendarList", { at: new Date().toISOString(), items });
  log.info(`calendar list refreshed (${items.length} calendars)`);
  return items;
}

/**
 * Match configured names against what Google actually returns.
 *
 * v1 compared exact lowercased strings, which is why "Family Events"
 * never matched — Google returns a curly apostrophe (U+2019) and the config
 * had a straight one. Normalising quotes and whitespace fixes that class of
 * bug permanently.
 *
 * Exported because calendar-name matching turned out not to be a
 * resolveCalendars()-only problem: sources/calendar.js's reconciliation and
 * scripts/cleanup-orphaned-calendar-items.js both compare a stored item's
 * recorded calendar name against a fresh list from Google too, and hit the
 * exact same curly-quote class of bug — "Sydney's Demands" (an apostrophe
 * name if there ever was one) read as orphaned everywhere it was actually
 * still a real, unchanged calendar.
 */
export function normaliseName(s) {
  return String(s || "")
    .replace(/[‘’ʼ]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, "-")
    .replace(/&/g, "and")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

export async function resolveCalendars(targetNames, { force = false } = {}) {
  const all = await getCalendarList({ force });
  const wanted = targetNames.map(normaliseName);
  const matched = all.filter((c) => wanted.includes(normaliseName(c.summary)));

  const missing = targetNames.filter(
    (name) => !matched.some((c) => normaliseName(c.summary) === normaliseName(name))
  );
  if (missing.length) {
    log.warn(`calendars not found: ${missing.join(", ")}`);
    log.warn(`available: ${all.map((c) => c.summary).join(" | ")}`);
  }
  return { matched, missing, available: all.map((c) => c.summary) };
}

/**
 * One calendar's events over [timeMin, timeMax], paginated to completion.
 * Google caps a single events.list response at `maxResults` regardless of
 * how many events actually match the window — the old code read page 1 and
 * stopped, so any calendar carrying more than `maxResults` events in the
 * horizon silently lost everything past that cutoff. That's a plausible
 * reason an all-day event (or anything else) can just never show up: not
 * corrupted, not misdated, just past the first page and never fetched.
 * `pages < hardCap` is purely a runaway-loop backstop against a
 * pathological response that keeps handing back a token forever — it is
 * not expected to bind for an ordinary personal calendar over ~2 weeks.
 */
async function fetchCalendarEvents(cal, { timeMin, timeMax, token, maxResults }) {
  const items = [];
  let pageToken;
  let pages = 0;
  const hardCap = 20;
  do {
    const data = await authed(
      `https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(cal.id)}/events`,
      {
        timeMin: timeMin.toISOString(),
        timeMax: timeMax.toISOString(),
        singleEvents: true,
        orderBy: "startTime",
        maxResults,
        ...(pageToken ? { pageToken } : {}),
      },
      token
    );
    items.push(...(data.items || []));
    pageToken = data.nextPageToken;
    pages++;
  } while (pageToken && pages < hardCap);

  return items
    .filter((e) => e.status !== "cancelled")
    .map((e) => ({
      id: e.id,
      calendarId: cal.id,
      calendarName: cal.summary,
      calendarColor: cal.color || null,
      summary: e.summary || "(no title)",
      description: e.description || "",
      location: e.location || "",
      htmlLink: e.htmlLink || "",
      allDay: Boolean(e.start?.date),
      start: e.start?.dateTime || e.start?.date,
      end: e.end?.dateTime || e.end?.date,
      attendees: e.attendees?.length || 0,
      recurringEventId: e.recurringEventId || null,
      updated: e.updated || "",
    }));
}

export async function getEvents(calendars, { timeMin, timeMax, maxResults = 250 }) {
  const token = await getAccessToken();

  const chunks = await pool(calendars, 4, async (cal) =>
    fetchCalendarEvents(cal, { timeMin, timeMax, token, maxResults })
  );

  // pool() swallows a per-calendar failure and leaves that slot null (see
  // pool() above) rather than throwing — one calendar's timeout must never
  // take the whole pull down. But a null slot is indistinguishable from "this
  // calendar genuinely has zero events right now" unless it's reported back:
  // collectCalendar() uses "an event that used to come back but didn't this
  // time" to detect a real deletion, and treating a failed fetch the same
  // way would read every event on that calendar as deleted.
  const failedCalendarIds = calendars.filter((cal, i) => chunks[i] === null).map((c) => c.id);

  return {
    events: chunks.filter(Boolean).flat().sort((a, b) => new Date(a.start) - new Date(b.start)),
    failedCalendarIds,
  };
}
